name: nse-eod-data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python version needed

      - name: install dependencies
        run:  pip install -r requirements.txt

    
      - name: execute py script # run endofday_data.py to get the latest data
        run: pipenv run python endofday_data.py

      - name: commit & push files
        run: |
          git config --local user.email ajakzhedgar@gmail.com
          git config --local user.name ajakaiye33
          git add -A
          timestamp=$(date --rfc-2822)
          git commit -m "updated data:${timestamp}" || exit 0
          git push
